# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db35c4ae24edf2575bc80820316980c6c69a51e412ecea70cf0c8709d1218e19858af0ba145837d2a0da5ccc455123f158159d62a2037389c976dac0e9299597

test:
  secret_key_base: 367ca1ecce25ae1b24953dea788bde226be0b749423c6e8dfeab11186642cd7a22048e07c22a23e166d3d0ead91cab4cc15df1336336f41d8765c6fc05a192b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
